name: Build Tweak
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos‑14
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          export THEOS=$HOME/theos
          curl -fsSL https://theos.dev/install.sh | bash
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Link system iPhoneOS SDK
        run: |
          mkdir -p $THEOS/sdks
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk $THEOS/sdks/iPhoneOS15.2.sdk

      - name: Build
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: built-deb
          path: packages/*.deb